/** Regenerates popup/icons.js from @iconify-json/ant-design.
 *
 * MV3 forbids remote resources and the popup has no bundler, so the icon paths
 * are checked in as static data. Re-run this only when MAP changes. */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const set = JSON.parse(
  readFileSync(resolve(here, '../../../node_modules/@iconify-json/ant-design/icons.json'), 'utf8'),
);

const MAP = {
  videoCamera: 'video-camera-outlined',
  camera: 'camera-outlined',
  setting: 'setting-outlined',
  chrome: 'chrome-outlined',
  desktop: 'desktop-outlined',
  expand: 'expand-outlined',
  audio: 'audio-outlined',
  sound: 'sound-outlined',
  user: 'user-outlined',
  right: 'right-outlined',
  left: 'left-outlined',
  close: 'close-outlined',
  check: 'check-outlined',
  minus: 'minus-outlined',
  link: 'link-outlined',
  copy: 'copy-outlined',
  download: 'download-outlined',
  scissor: 'scissor-outlined',
  cloudUpload: 'cloud-upload-outlined',
  folder: 'folder-outlined',
  delete: 'delete-outlined',
  pause: 'pause-outlined',
  play: 'caret-right-outlined',
  reload: 'reload-outlined',
  warning: 'warning-outlined',
};

const out = {};
for (const [key, name] of Object.entries(MAP)) {
  const icon = set.icons[name];
  if (!icon) throw new Error(`missing icon in @iconify-json/ant-design: ${name}`);
  out[key] = {
    body: icon.body,
    w: icon.width ?? set.width ?? 24,
    h: icon.height ?? set.height ?? 24,
  };
}

const file = `/* GENERATED by scripts/build-icons.mjs — do not edit by hand.
 * MV3 forbids remote resources and the popup has no bundler, so these paths
 * are checked in deliberately. Regenerate with:
 *   node apps/extension/scripts/build-icons.mjs */
export const ICONS = ${JSON.stringify(out, null, 2)};

export function icon(name, size = 16) {
  const i = ICONS[name];
  if (!i) throw new Error('unknown icon: ' + name);
  return '<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" '
    + 'width="' + size + '" height="' + size + '" '
    + 'viewBox="0 0 ' + i.w + ' ' + i.h + '" fill="currentColor">'
    + i.body
    + '</svg>';
}
`;

writeFileSync(resolve(here, '../popup/icons.js'), file);
console.log(`wrote ${Object.keys(out).length} icons to popup/icons.js`);
