/* SEO W5 — generate public/sitemap.xml from the route list.
 *
 * The sitemap was hand-maintained, which is why its newest `<lastmod>` was
 * 2026-05-07 while /privacy and /terms said "Updated August 2026" in their own
 * body copy, and why keeping 48 URLs in step across four files was a manual
 * chore. This runs as the first step of `build` and `build:prerender`.
 *
 * Output goes to public/ rather than dist/ for two reasons: vite copies public/
 * verbatim so it lands in dist anyway, and src/__tests__/routes.test.ts asserts
 * against the committed file — writing only to dist would leave the test reading
 * a stale sitemap. The generated file is meant to be committed; a diff after a
 * build is the signal that a route or a post date changed.
 *
 *   node scripts/generate-sitemap.mjs
 */

import { writeFileSync, readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { getAllRoutes, toAbsoluteUrl } from '../routes.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../public/sitemap.xml');

function build() {
  const routes = getAllRoutes();

  const body = routes
    .map(({ route, lastmod }) =>
      `  <url>\n    <loc>${toAbsoluteUrl(route)}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </url>`)
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs from routes.mjs + src/data/blogData.ts.
     Do not hand-edit: add the route to routes.mjs (or the post to blogData.ts) and rebuild. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;
}

const xml = build();

let previous = '';
try {
  previous = readFileSync(OUT, 'utf8');
} catch {
  // first run
}

writeFileSync(OUT, xml);

const count = (xml.match(/<loc>/g) || []).length;
const changed = previous !== xml;
console.log(`[sitemap] ${count} URLs -> public/sitemap.xml${changed ? ' (changed — commit it)' : ' (unchanged)'}`);
